dg_unified:
  outputs:
    prod:
      account: MKEHLMP-KSB52264
      database: PUBLIC_PRODUCTION_DB
      private_key_path: "{{ env_var('SNOWFLAKE_RSA_PRIVATE_KEY_PATH') }}"
      role: DATA_MODEL_ROLE
      schema: SNOWPLOW_DBT
      threads: 1
      type: snowflake
      user: SNOWPLOW_DATA_MODEL_USER
      warehouse: SNOWPLOW_DATA_MODEL_WAREHOUSE
      client_session_keep_alive: true
  target: prod
