# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'snowplow_segment_migration'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'snowplow_segment_migration'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models
models:
  snowplow_segment_migration:
    base:
      +materialized: view
    assembly:
      +materialized: table
    sources:
      +enabled: true

vars:
  # Schema URLs for Snowplow OOTB contexts
  snowplow_context_schemas:
    mobile_context: 'iglu:com.snowplowanalytics.snowplow/mobile_context/jsonschema/1-0-3'
    mobile_application: 'iglu:com.snowplowanalytics.mobile/application/jsonschema/1-0-0'

  # Schema URLs for custom contexts  
  custom_context_schemas:
    ui_element: 'iglu:com.desiringgod/ui_element/jsonschema/1-0-0'
    email_list: 'iglu:com.desiringgod/email_list/jsonschema/1-0-0'
    resource: 'iglu:com.desiringgod/resource/jsonschema/1-0-0'

    # OOTB Contexts to apply which map from Segment columns into Snowplow contexts
  snowplow_context_definitions:
    mobile_context:
      osVersion: 'context_os_version'
      osType: 'context_os_name'
      deviceManufacturer: 'context_device_manufacturer'
      deviceModel: 'context_device_model'
      carrier: 'context_network_carrier'
    mobile_application:
      build: 'context_app_build'
      version: 'context_app_version'
    
  # Custom contexts to apply which map from Segment columns into Snowplow contexts
  custom_context_definitions:
    resource:
      resource_id: 'resource_id'
      resource_title: ['book_name', 'title', 'page_title', 'context_page_title']

  include_sources:
    - ask_pastor_john
    - production_desiring_god_website

  use_explicit_columns: true # Set to false to select all cols in superset of sources

  app_id_mapping:
    production_desiring_god_website: 'www-rails'
    ruby_production_desiring_god_website: 'www-rails'
    hub: 'api'
    ask_pastor_john: 'apj_android'
    ask_pastor_john_ios: 'apj_ios'
    sermon_of_the_day_android: 'sotd_android'
    sermon_of_the_day_ios: 'sotd_ios'
    solid_joys_android: 'sj_android'
    solid_joys_ios: 'sj_ios'

  column_rename_map:
    app_id: 'context_app_name'
    domain_userid: 'anonymous_id'
    event_id: 'id'
    user_id: ['user_id', 'userid', 'user_testing']
    collector_tstamp: 'received_at'
    br_lang: 'context_locale'
    br_cookies: 'browser_cookie_enabled'
    derived_tstamp: 'timestamp'
    dvce_created_tstamp: 'original_timestamp'
    dvce_screenheight: ['context_screen_height', 'screen_height']
    dvce_screenwidth: ['context_screen_width', 'screen_width']
    dvce_sent_tstamp: 'sent_at'
    event: 'event'
    event_vendor: 'context_app_namespace'
    name_tracker: 'context_library_name'
    os_timezone: 'context_timezone'
    page_urlquery: 'context_page_search'
    user_ipaddress: 'context_ip'
    useragent: ['context_user_agent', 'user_agent']
    v_tracker: 'context_library_version'
    mkt_content: [
      'context_campaign_content',
      'context_campaign_bycontent',
      'context_campaign_campaig_n',
      'context_campaign_co_ffgf_zaax6_qmbx_acf_zref_mf_abg_mswl_v7ntent',
      'context_campaign_condrtent',
      'context_campaign_cont1nt',
      'context_campaign_contaent',
      'context_campaign_contenent',
      'context_campaign_contenguyt',
      'context_campaign_contentbvb',
      'context_campaign_contentn',
      'context_campaign_contentrded',
      'context_campaign_goocontent',
      'context_campaign_ontent',
      'context_campaign_tm_content',
      'context_campaign_cyou_20tubeampaign',
      'context_campaign_diun'
    ]
    mkt_medium: [
      'context_campaign_medium',
      'context_campaign_campaign_medium',
      'context_campaign_utm_medium',
      'context_campaign_utm_mediun',
      'context_campaign_mediun',
      'context_campaign_3butm_medium',
      'context_campaign_diun',
      'context_campaign_maedium',
      'context_campaign_mdium',
      'context_campaign_mecksondium',
      'context_campaign_medikrogerum',
      'context_campaign_medim',
      'context_campaign_mediu',
      'context_campaign_mediu_im',
      'context_campaign_mediucm',
      'context_campaign_mediugooglm',
      'context_campaign_medium_20',
      'context_campaign_medium7',
      'context_campaign_mediumex',
      'context_campaign_mediumi',
      'context_campaign_mediumins',
      'context_campaign_medrium',
      'context_campaign_medum',
      'context_campaign_meium',
      'context_campaign_q_c3_a5utm_medium',
      'context_campaign_robedium',
      'context_campaign_sdium',
      'context_campaign_tm_medium',
      'context_campaign_tm_mediun',
      'context_campaign_yamedium',
      'context_campaign_mediufm',
      'context_campaign_amedium'
    ]
    mkt_name: ['context_campaign_campaign_name', 'context_campaign_name']
    mkt_term: [
      'context_campaign_term',
      'context_campaign_utm_term',
      'context_campaign_t_20erm',
      'context_campaign_term_20'
    ]
    mkt_source: [
      'context_campaign_source',
      'context_campaign_utm_source',
      'context_campaign_campaign_source',
      'context_campaign_content_source',
      'context_campaign_utm_content',
      'context_campaign_3butm_source',
      'context_campaign_med_urce',
      'context_campaign_ource',
      'context_campaign_romans_2012source',
      'context_campaign_rysocuurce',
      'context_campaign_s',
      'context_campaign_s_cvource',
      'context_campaign_siurce',
      'context_campaign_so_20urce',
      'context_campaign_so_comurce',
      'context_campaign_so_urce',
      'context_campaign_socheraw_20cource',
      'context_campaign_sohurce',
      'context_campaign_sorce',
      'context_campaign_souce',
      'context_campaign_sourc',
      'context_campaign_sourc_gbe',
      'context_campaign_source_0a',
      'context_campaign_source_20',
      'context_campaign_source_sc',
      'context_campaign_sourceh',
      'context_campaign_sourcgoo',
      'context_campaign_sourcye',
      'context_campaign_soure',
      'context_campaign_surce',
      'context_campaign_tm_source',
      'context_campaign_utm_sourcesource'
    ]
    mkt_campaign: [
      'context_campaign_utm_campaign',
      'context_campaign_campaign',
      'context_campaign_20campaign',
      'context_campaign_3butm_campaign',
      'context_campaign_3butm_medium',
      'context_campaign_9f_a5_b0utm_campaign',
      'context_campaign_ampaign',
      'context_campaign_c_20ampaign',
      'context_campaign_c_ampaign',
      'context_campaign_c_fnbampaign',
      'context_campaign_cacalmpaign',
      'context_campaign_cagmpaign',
      'context_campaign_cagrand_20rapids_20newsmpaign',
      'context_campaign_cajohn_20mccain_20bookmpaign',
      'context_campaign_cam_paign',
      'context_campaign_camaign',
      'context_campaign_camapaign',
      'context_campaign_camfpaign',
      'context_campaign_camoaign',
      'context_campaign_camp_20bc_20aign',
      'context_campaign_campa_20icky_20and_20minnie_20mouse_20go_20on_20a_20picnic_20youtubegn',
      'context_campaign_campagn',
      'context_campaign_campai_20gn',
      'context_campaign_campaig',
      'context_campaign_campaign_ce_91',
      'context_campaign_campaigne',
      'context_campaign_campaignp',
      'context_campaign_campaignt',
      'context_campaign_campaignv',
      'context_campaign_campain',
      'context_campaign_campaing',
      'context_campaign_campazay_20flowers_20injuryign',
      'context_campaign_campccfaign',
      'context_campaign_campsaign',
      'context_campaign_campsign',
      'context_campaign_cazmpaign',
      'context_campaign_cmpaign',
      'context_campaign_cncdmvmpaign',
      'context_campaign_compaign',
      'context_campaign_cyou_20tubeampaign',
      'context_campaign_jimmie_20mcnair_20brandon_20ms',
      'context_campaign_m_content',
      'context_campaign_majesticmusic_com',
      'context_campaign_spiritdailyampaign',
      'context_campaign_tm_campaign',
      'context_campaign_co_ffgf_zaax6_qmbx_acf_zref_mf_abg_mswl_v7ntent'
    ]
    page_title: ['context_page_title', 'title', 'page_title']
    page_urlpath: ['context_page_path', 'path', 'page_path']
    page_referrer: ['context_page_referrer', 'referrer']
    page_url: ['page_url', 'url', 'context_page_url']
    event_name: ['event_text', 'event', 'name']

  # Custom contexts which are not present from Segment data which map into custom contexts
  custom_context_mappings:
    # Button Click Events
    'production_desiring_god_website.main_menu_close_click':
      ui_element_context: [{"action": "close", "name": "header-menu-drawer"}]
    
    'production_desiring_god_website.search_icon_close_click':
      ui_element_context: [{"action": "close", "name": "header-search"}]
    
    'production_desiring_god_website.download_book_click':
      ui_element_context: [{"action": "open", "name": "download-book-popup"}]
    
    'production_desiring_god_website.main_menu_open_click':
      ui_element_context: [{"action": "open", "name": "header-menu-drawer"}]
    
    'production_desiring_god_website.search_icon_open_click':
      ui_element_context: [{"action": "open", "name": "header-search"}]
    
    'production_desiring_god_website.purchase_book_click':
      ui_element_context: [{"action": "open", "name": "purchase-book-popup"}]
    
    'production_desiring_god_website.header_navigation_click':
      ui_element_context: [{"name": "header-navigation"}]
    
    'production_desiring_god_website.subscribe_click':
      ui_element_context: [{"name": "look-at-the-book-subscribe-menu-toggle"}, {"name": "messages-by-desiring-god-subscribe-menu-toggle"}, {"name": "ask-pastor-john-subscribe-menu-toggle"}, {"name": "solid-joys-subscribe-menu-toggle"}, {"name": "articles-by-desiring-god-subscribe-menu-toggle"}, {"name": "light-truth-subscribe-menu-toggle"}]

    # Form Submit Events with Email List Context Only
    'production_desiring_god_website.apj_email_form_submit':
      email_list_context: [{"id": 4, "name": "Ask Pastor John"}]
    
    'production_desiring_god_website.article_email_form_submit':
      email_list_context: [{"id": 11, "name": "Articles by Desiring God"}]
    
    'production_desiring_god_website.here_we_stand_email_form_submit':
      email_list_context: [{"id": 46, "name": "Here We Stand"}]
    
    'production_desiring_god_website.lab_email_form_submit':
      email_list_context: [{"id": 6, "name": "Look at the Book"}]
    
    'production_desiring_god_website.sj_email_form_submit':
      email_list_context: [{"id": 7, "name": "Solid Joys"}]
    
    'production_desiring_god_website.subscribe_stand_page_email_form_submit':
      email_list_context: [{"id": 46, "name": "Here We Stand"}]

    # Form Submit Events with Both UI Element and Email List Contexts  
    'production_desiring_god_website.email_form_submit':
      ui_element_context: [{"name": "email-subscribe-form"}]
      email_list_context: [{"id": 1, "name": "Daily Digest"}, {"id": 3, "name": "Weekly Digest"}]
    
    'production_desiring_god_website.email_updates_form_submit':
      email_list_context: [{"id": 1, "name": "Daily Digest"}, {"id": 3, "name": "Weekly Digest"}]
    
    'production_desiring_god_website.footer_email_updates_form_submit':
      ui_element_context: [{"name": "footer-subscribe-form"}]
      email_list_context: [{"id": 1, "name": "Daily Digest"}, {"id": 3, "name": "Weekly Digest"}]
    
    'production_desiring_god_website.homepage_email_form_submit':
      ui_element_context: [{"name": "daily-email-form"}]
      email_list_context: [{"id": 1, "name": "Daily Digest"}, {"id": 3, "name": "Weekly Digest"}]
    
    'production_desiring_god_website.subscribe_page_email_form_submit':
      email_list_context: [{"id": 1, "name": "Daily Digest"}, {"id": 3, "name": "Weekly Digest"}]
    
    'production_desiring_god_website.donate_submit':
      ui_element_context: [{"name": "give-form"}]
    
    'production_desiring_god_website.search_bar_submit':
      ui_element_context: [{"name": "header-search-submit"}]

    # Site Search Events
    'production_desiring_god_website.search_submit':
      ui_element_context: [{"name": "header-search-submit"}]

    # Link Click Events
    'production_desiring_god_website.banner_click':
      ui_element_context: [{"name": "top-banner"}]
    
    'production_desiring_god_website.ctp_more_on_topic_click':
      ui_element_context: [{"name": "more-on-topic-link"}]
    
    'production_desiring_god_website.ctp_other_topics_click':
      ui_element_context: [{"name": "other-topics"}]
    
    'production_desiring_god_website.ctp_related_topics_click':
      ui_element_context: [{"name": "related-topic"}]
    
    'production_desiring_god_website.desiring_god_social_outbound_click':
      ui_element_context: [{"name": "footer-facebook"}, {"name": "footer-instagram"}, {"name": "footer-youtube"}, {"name": "footer-twitter"}]
    
    'production_desiring_god_website.donate_footer_click':
      ui_element_context: [{"name": "footer-donate"}]
    
    'production_desiring_god_website.donate_header_click':
      ui_element_context: [{"name": "main-menu-navigation"}]
    
    'production_desiring_god_website.download_book_action_click':
      ui_element_context: [{"name": "download-book-pdf"}, {"name": "download-book-epub"}, {"name": "download-book-mobi"}, {"name": "download-book-mp3"}]
    
    'production_desiring_god_website.here_we_stand_i_tunes_click':
      ui_element_context: [{"name": "here-we-stand-apple-podcasts"}]
    
    'production_desiring_god_website.homepage_more_click':
      ui_element_context: [{"name": "homepage-more-top"}]
    
    'production_desiring_god_website.homepage_more_of_newest_click':
      ui_element_context: [{"name": "homepage-more-bottom"}]
    
    'production_desiring_god_website.main_menu_navigation_click':
      ui_element_context: [{"name": "main-menu-navigation"}]
    
    'production_desiring_god_website.more_resources_click':
      ui_element_context: [{"name": "more-resources"}]
    
    'production_desiring_god_website.next_lab_click':
      ui_element_context: [{"name": "next-lab"}]
    
    'production_desiring_god_website.previous_lab_click':
      ui_element_context: [{"name": "previous-lab"}]
    
    'production_desiring_god_website.purchase_book_outbound_click':
      ui_element_context: [{"name": "purchase-book-paperback"}, {"name": "purchase-book-hardcover"}, {"name": "purchase-book-kindle"}, {"name": "purchase-book-audiobook"}]
    
    'production_desiring_god_website.series_cta_apple_podcasts_click':
      ui_element_context: [{"name": "here-we-stand-apple-podcasts"}]
    
    'production_desiring_god_website.series_cta_podcasts_da_apple_click':
      ui_element_context: [{"name": "here-we-stand-apple-podcasts"}]
    
    'production_desiring_god_website.series_cta_podcasts_de_apple_click':
      ui_element_context: [{"name": "here-we-stand-apple-podcasts"}]
    
    'production_desiring_god_website.series_cta_podcast_di_apple_click':
      ui_element_context: [{"name": "here-we-stand-apple-podcasts"}]
    
    'production_desiring_god_website.series_cta_e_book_click':
      ui_element_context: [{"name": "solid-joys-ebook"}]
    
    'production_desiring_god_website.series_cta_e_book_en_click':
      ui_element_context: [{"name": "solid-joys-ebook"}]
    
    'production_desiring_god_website.series_cta_libro_electronico_click':
      ui_element_context: [{"name": "solid-joys-ebook"}]
    
    'production_desiring_god_website.series_cta_libro_electr_nico_click':
      ui_element_context: [{"name": "solid-joys-ebook"}]
    
    'production_desiring_god_website.series_cta_paperback_click':
      ui_element_context: [{"name": "solid-joys-paperback"}]
    
    'production_desiring_god_website.series_cta_spotify_click':
      ui_element_context: [{"name": "here-we-stand-spotify"}, {"name": "solid-joys-spotify"}]
    
    'production_desiring_god_website.series_cta_spottizzare_click':
      ui_element_context: [{"name": "here-we-stand-spotify"}, {"name": "solid-joys-spotify"}]
    
    'production_desiring_god_website.subscribe_outbound_click':
      ui_element_context: [{"action": "subscribe", "name": "ask-pastor-john-subscribe-menu"}, {"action": "subscribe", "name": "solid-joys-subscribe-menu"}, {"action": "subscribe", "name": "light-truth-subscribe-menu"}, {"action": "subscribe", "name": "look-at-the-book-subscribe-menu"}, {"action": "subscribe", "name": "articles-by-desiring-god-subscribe-menu"}, {"action": "subscribe", "name": "messages-by-desiring-god-subscribe-menu"}]
    
    'production_desiring_god_website.villain_and_sidekick_click':
      ui_element_context: [{"name": "sidekick"}, {"name": "villain"}]