
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'snowplow_segment_migration'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'snowplow_segment_migration'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/
# directory as views. These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.
models:
  snowplow_segment_migration:
    # Config indicated by + and applies to all files under models/example/
    base:
      +materialized: view
    assembly:
      +materialized: table
    sources:
      +enabled: true

vars:
  # unmapped_event_context_schema: 'iglu:com.desiringgod/unmapped_segment_data/jsonschema/1-0-0'
  contexts_com_snowplowanalytics_snowplow_mobile_context_1: 'iglu:com.snowplowanalytics.snowplow/mobile_context/jsonschema/1-0-3'
  contexts_com_snowplowanalytics_mobile_application_1: 'iglu:com.snowplowanalytics.mobile/application/jsonschema/1-0-0'

  column_rename_map:
    domain_userid: 'anonymous_id'
    event_id: 'id'
    userid: 'user_id'
    collector_tstamp: 'received_at'
    br_lang: 'context_locale'
    br_cookies: 'browser_cookie_enabled'
    derived_tstamp: 'timestamp'
    dvce_created_tstamp: 'original_timestamp'
    dvce_screenheight: 'context_screen_height'
    dvce_screenwidth: 'context_screen_width'
    dvce_sent_tstamp: 'sent_at'
    event_vendor: 'context_app_namespace'
    name_tracker: 'context_library_name'
    os_timezone: 'context_timezone'
    user_ipaddress: 'context_ip'
    useragent: 'context_user_agent'
    v_tracker: 'context_library_version'
    page_title: ['context_page_title', 'title']
    page_urlpath: ['context_page_path', 'path']
    page_referrer: ['context_page_referrer', 'referrer']
    page_url: ['page_url', 'url', 'context_page_url']
    event: ['event_text', 'event', 'name']

  context_definitions:
    contexts_com_snowplowanalytics_snowplow_mobile_context_1:
      osVersion: 'context_os_version'
      osType: 'context_os_name'
      deviceManufacturer: 'context_device_manufacturer'
      deviceModel: 'context_device_model'
    contexts_com_snowplowanalytics_mobile_application_1:
      build: 'context_app_build'
      version: 'context_app_version'

  include_sources:
    - ask_pastor_john
    - production_desiring_god_website

  use_explicit_columns: true # Set to false to select all cols in superset of sources

  event_rename_map:
    page_view:
      - '%PAGES'
    screen_view:
      - '%SCREENS'
    link_click:
      - '%ACCOUNT_CLICK'
      - '%BANNER_CLICK'
      - '%BOOK_CLICK'
      - '%BROWSE_CLICK'
      - '%CTP_A_TOPICAL_SURVEY_CLICK'
      - '%CTP_MORE_ON_TOPIC_CLICK'
      - '%CTP_OTHER_TOPICS_CLICK'
      - '%CTP_RELATED_TOPICS_CLICK'
      - '%CTP_RESOURCE_CLICK'
      - '%CTP_SHARE_WITH_OTHERS_CLICK'
      - '%CTP_VIEW_MORE_ON_THIS_TOPIC_CLICK'
      - '%C_C_ALBANIAN_CLICK'
      - '%C_C_ARABIC_CLICK'
      - '%C_C_FRENCH_CLICK'
      - '%C_C_GERMAN_CLICK'
      - '%C_C_INDONESIAN_CLICK'
      - '%C_C_ITALIAN_CLICK'
      - '%C_C_KOREAN_CLICK'
      - '%C_C_OL_CLICK'
      - '%C_C_POLISH_CLICK'
      - '%C_C_PORTUGUESE_CLICK'
      - '%C_C_RUSSIAN_CLICK'
      - '%C_C_SPANISH_CLICK'
      - '%C_C_URDU_CLICK'
      - '%DESIRING_GOD_SOCIAL_OUTBOUND_CLICK'
      - '%DONATE_FOOTER_CLICK'
      - '%DONATE_HEADER_CLICK'
      - '%DOWNLOAD_APP_OUTBOUND_CLICK'
      - '%DOWNLOAD_BOOK_ACTION_CLICK'
      - '%FINANCIAL_STEWARDSHIP_CLICK'
      - '%FOOTER_LEARN_MORE_CLICK'
      - '%HERE_WE_STAND_INVITE_OTHERS_SHARE_CLICK'
      - '%HERE_WE_STAND_I_TUNES_CLICK'
      - '%HERE_WE_STAND_RSS_CLICK'
      - '%HOMEPAGE_FEATURED_RESOURCE_CLICK'
      - '%HOMEPAGE_MORE_CLICK'
      - '%HOMEPAGE_MORE_OF_NEWEST_CLICK'
      - '%HOMEPAGE_MORE_OF_RECENT_CLICK'
      - '%JOHN_PIPER_SOCIAL_OUTBOUND_CLICK'
      - '%MAIN_MENU_NAVIGATION_CLICK'
      - '%MORE_RESOURCES_CLICK'
      - '%NEXT_LAB_CLICK'
      - '%PLAY_CLICK'
      - '%PREVIOUS_LAB_CLICK'
      - '%PURCHASE_BOOK_OUTBOUND_CLICK'
      - '%RESOURCE_SHARE_ICON_CLICK'
      - '%RESOURCE_SHARE_SOCIAL_CLICK'
      - '%SERIES_CTA_APPLE_PODCASTS_CLICK'
      - '%SERIES_CTA_PODCASTS_DA_APPLE_CLICK'
      - '%SERIES_CTA_PODCASTS_DE_APPLE_CLICK'
      - '%SERIES_CTA_PODCAST_DI_APPLE_CLICK'
      - '%SERIES_CTA_BROWSE_ALL_PROFILES_CLICK'
      - '%SERIES_CTA_BLADER_DOOR_ALLE_PROFIELEN_CLICK'
      - '%SERIES_CTA_BUSCAR_TODOS_LOS_PERFILES_CLICK'
      - '%SERIES_CTA_EXAMINAR_TODOS_LOS_PERFILES_CLICK'
      - '%SERIES_CTA_EXPLORAR_TODOS_LOS_PERFILES_CLICK'
      - '%SERIES_CTA_PROCURAR_TODOS_OS_PERFIS_CLICK'
      - '%SERIES_CTA_I_BROWSE_ANG_LAHAT_NG_PROFILE_CLICK'
      - '%SERIES_CTA_PARCOURIR_TOUS_LES_PROFILS_CLICK'
      - '%SERIES_CTA_CLICK'
      - '%SERIES_CTA_E_BOOK_CLICK'
      - '%SERIES_CTA_E_BOOK_EN_CLICK'
      - '%SERIES_CTA_LIBRO_ELECTRONICO_CLICK'
      - '%SERIES_CTA_LIBRO_ELECTR_NICO_CLICK'
      - '%SERIES_CTA_ITUNES_CLICK'
      - '%SERIES_CTA_I_TUNES_2_I_TUNES_CLICK'
      - '%SERIES_CTA_I_TUNES_CLICK'
      - '%SERIES_CTA_I_TUNES_EN_INGL_S_CLICK'
      - '%SERIES_CTA_I_TUNES_I_TUNES_CLICK'
      - '%SERIES_CTA_PAPERBACK_CLICK'
      - '%SERIES_CTA_RSS_CLICK'
      - '%SERIES_CTA_RSS_RSS_CLICK'
      - '%SERIES_CTA_R_STICA_CLICK'
      - '%SERIES_CTA_SPOTIFY_CLICK'
      - '%SERIES_CTA_SPOTTIZZARE_CLICK'
      - '%SHARE_WITH_OTHERS_CLICK'
      - '%SUBSCRIBE_OUTBOUND_CLICK'
      - '%TRY_SEARCHING_CLICK'
      - '%VILLAIN_AND_SIDEKICK_CLICK'
    button_click:
      - '%MAIN_MENU_CLOSE_CLICK'
      - '%SEARCH_ICON_CLOSE_CLICK'
      - '%DOWNLOAD_BOOK_CLICK'
      - '%MAIN_MENU_OPEN_CLICK'
      - '%SEARCH_ICON_OPEN_CLICK'
      - '%PURCHASE_BOOK_CLICK'
      - '%HEADER_NAVIGATION_CLICK'
      - '%SUBSCRIBE_CLICK'
    form_submit:
      - '%APJ_EMAIL_FORM_SUBMIT'
      - '%ARTICLE_EMAIL_FORM_SUBMIT'
      - '%EMAIL_FORM_SUBMIT'
      - '%EMAIL_UPDATES_FORM_SUBMIT'
      - '%FOOTER_EMAIL_UPDATES_FORM_SUBMIT'
      - '%HERE_WE_STAND_EMAIL_FORM_SUBMIT'
      - '%HOMEPAGE_EMAIL_FORM_SUBMIT'
      - '%LAB_EMAIL_FORM_SUBMIT'
      - '%SJ_EMAIL_FORM_SUBMIT'
      - '%SUBSCRIBE_PAGE_EMAIL_FORM_SUBMIT'
      - '%SUBSCRIBE_STAND_PAGE_EMAIL_FORM_SUBMIT'
      - '%LOGIN_FORM_SUBMIT'
      - '%SEARCH_BAR_SUBMIT'
      - '%CREATE_AN_ACCOUNT_FORM_SUBMIT'
    subscribe:
      - '%EMAIL_SUBSCRIBED'
    unsubscribe:
      - '%EMAIL_UNSUBSCRIBED'
